<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Produit;
use Illuminate\Database\Seeder;

class ProduitsSeeder extends Seeder
{
    public function run(): void
    {
        $produits = [

            // ── Petit-Déjeuner ────────────────────────────────────────────────
            [
                'category'       => 'Petit-Déjeuner',
                'name'           => 'Petit-déjeuner marocain traditionnel',
                'name_ar'        => 'الفطور المغربي التقليدي',
                'description'    => 'Pain maison, msemen, crêpe, œufs, fromage, miel, huile d\'olive, beurre, jus d\'orange, thé à la menthe ou café',
                'image'          => 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 70.00,
                'price_achat'    => 28.00,
                'stock_quantity' => 50,
                'alert_stock'    => 10,
                'unit'           => 'plateau',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Petit-Déjeuner',
                'name'           => 'Petit-déjeuner Healthy',
                'name_ar'        => 'فطور صحي',
                'description'    => 'Yaourt nature, muesli, fruits frais, jus détox, thé ou café',
                'image'          => 'https://images.unsplash.com/photo-1490818387583-1baba5e638af?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 70.00,
                'price_achat'    => 25.00,
                'stock_quantity' => 30,
                'alert_stock'    => 8,
                'unit'           => 'plateau',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Petit-Déjeuner',
                'name'           => 'Petit-déjeuner Enfant',
                'name_ar'        => 'فطور الأطفال',
                'description'    => 'Pancakes maison, céréales, lait, jus',
                'image'          => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 50.00,
                'price_achat'    => 18.00,
                'stock_quantity' => 20,
                'alert_stock'    => 5,
                'unit'           => 'plateau',
                'kitchen_active' => 1,
            ],

            // ── Boissons ──────────────────────────────────────────────────────
            [
                'category'       => 'Boissons',
                'name'           => 'Eau 50 cl',
                'name_ar'        => 'ماء معدني 50 سل',
                'description'    => 'Eau minérale 50 cl',
                'image'          => 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 10.00,
                'price_achat'    => 3.00,
                'stock_quantity' => 120,
                'alert_stock'    => 24,
                'unit'           => 'bouteille',
                'kitchen_active' => 0,
            ],
            [
                'category'       => 'Boissons',
                'name'           => 'Eau 1,5 L',
                'name_ar'        => 'ماء معدني 1.5 لتر',
                'description'    => 'Eau minérale 1,5 litre',
                'image'          => 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 20.00,
                'price_achat'    => 6.00,
                'stock_quantity' => 80,
                'alert_stock'    => 16,
                'unit'           => 'bouteille',
                'kitchen_active' => 0,
            ],
            [
                'category'       => 'Boissons',
                'name'           => 'Soda',
                'name_ar'        => 'مشروب غازي',
                'description'    => 'Soda',
                'image'          => 'https://images.unsplash.com/photo-1624517452488-04b8df0291d7?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 20.00,
                'price_achat'    => 7.00,
                'stock_quantity' => 100,
                'alert_stock'    => 20,
                'unit'           => 'bouteille',
                'kitchen_active' => 0,
            ],
            [
                'category'       => 'Boissons',
                'name'           => 'Eau gazeuse',
                'name_ar'        => 'ماء فوار',
                'description'    => 'Eau gazeuse',
                'image'          => 'https://images.unsplash.com/photo-1568213816046-0ee1c42bd559?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 20.00,
                'price_achat'    => 6.00,
                'stock_quantity' => 60,
                'alert_stock'    => 12,
                'unit'           => 'bouteille',
                'kitchen_active' => 0,
            ],
            [
                'category'       => 'Boissons',
                'name'           => "Jus d'orange pressé",
                'name_ar'        => 'عصير برتقال طازج',
                'description'    => "Jus d'orange fraîchement pressé",
                'image'          => 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 30.00,
                'price_achat'    => 10.00,
                'stock_quantity' => 80,
                'alert_stock'    => 15,
                'unit'           => 'verre',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Boissons',
                'name'           => 'Jus Détox',
                'name_ar'        => 'عصير ديتوكس',
                'description'    => 'Citron, concombre & menthe',
                'image'          => 'https://images.unsplash.com/photo-1622597467836-f3e4b2e38dfc?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 35.00,
                'price_achat'    => 12.00,
                'stock_quantity' => 50,
                'alert_stock'    => 10,
                'unit'           => 'verre',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Boissons',
                'name'           => 'Mojito Maison',
                'name_ar'        => 'موهيتو منزلي',
                'description'    => 'Sans alcool',
                'image'          => 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 35.00,
                'price_achat'    => 12.00,
                'stock_quantity' => 50,
                'alert_stock'    => 10,
                'unit'           => 'verre',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Boissons',
                'name'           => 'Citronnade maison',
                'name_ar'        => 'ليمونادة منزلية',
                'description'    => 'Citronnade fraîche maison',
                'image'          => 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 35.00,
                'price_achat'    => 10.00,
                'stock_quantity' => 50,
                'alert_stock'    => 10,
                'unit'           => 'verre',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Boissons',
                'name'           => 'Ice Tea',
                'name_ar'        => 'شاي مثلج',
                'description'    => 'Ice Tea maison',
                'image'          => 'https://images.unsplash.com/photo-1499638673689-79a0b5115d87?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 25.00,
                'price_achat'    => 8.00,
                'stock_quantity' => 60,
                'alert_stock'    => 12,
                'unit'           => 'verre',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Boissons',
                'name'           => 'Thé à la menthe',
                'name_ar'        => 'أتاي بالنعناع',
                'description'    => 'Thé marocain à la menthe fraîche',
                'image'          => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 25.00,
                'price_achat'    => 5.00,
                'stock_quantity' => 200,
                'alert_stock'    => 30,
                'unit'           => 'théière',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Boissons',
                'name'           => 'Thé marocain aux herbes du jardin',
                'name_ar'        => 'أتاي بأعشاب الحديقة',
                'description'    => 'Thé marocain aux herbes fraîches de notre jardin',
                'image'          => 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 25.00,
                'price_achat'    => 6.00,
                'stock_quantity' => 150,
                'alert_stock'    => 25,
                'unit'           => 'théière',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Boissons',
                'name'           => 'Thé noir',
                'name_ar'        => 'شاي أسود',
                'description'    => 'Thé noir',
                'image'          => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 25.00,
                'price_achat'    => 5.00,
                'stock_quantity' => 100,
                'alert_stock'    => 20,
                'unit'           => 'tasse',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Boissons',
                'name'           => 'Café Expresso',
                'name_ar'        => 'قهوة إسبريسو',
                'description'    => 'Café Expresso',
                'image'          => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 20.00,
                'price_achat'    => 5.00,
                'stock_quantity' => 150,
                'alert_stock'    => 25,
                'unit'           => 'tasse',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Boissons',
                'name'           => 'Café au lait',
                'name_ar'        => 'قهوة بالحليب',
                'description'    => 'Café au lait',
                'image'          => 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 30.00,
                'price_achat'    => 8.00,
                'stock_quantity' => 100,
                'alert_stock'    => 20,
                'unit'           => 'tasse',
                'kitchen_active' => 1,
            ],

            // ── Déjeuner Léger (13h-15h) ──────────────────────────────────────
            [
                'category'       => 'Déjeuner Léger',
                'name'           => 'Salade marocaine',
                'name_ar'        => 'سلطة مغربية',
                'description'    => 'Salade marocaine fraîche',
                'image'          => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 35.00,
                'price_achat'    => 12.00,
                'stock_quantity' => 60,
                'alert_stock'    => 12,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Déjeuner Léger',
                'name'           => 'Entrée Oussoul Signature',
                'name_ar'        => 'مقبلات أصول',
                'description'    => '3 assortiments marocains — arômes de notre potager',
                'image'          => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 60.00,
                'price_achat'    => 20.00,
                'stock_quantity' => 40,
                'alert_stock'    => 8,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Déjeuner Léger',
                'name'           => 'Salade César Maison',
                'name_ar'        => 'سلطة سيزار منزلية',
                'description'    => 'Salade César maison',
                'image'          => 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 70.00,
                'price_achat'    => 25.00,
                'stock_quantity' => 30,
                'alert_stock'    => 6,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Déjeuner Léger',
                'name'           => 'Assiette de grillades mixtes',
                'name_ar'        => 'طبق مشاوي مشكلة',
                'description'    => 'Poulet, kefta, saucisse, frites maison et légumes du potager',
                'image'          => 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 135.00,
                'price_achat'    => 55.00,
                'stock_quantity' => 25,
                'alert_stock'    => 5,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Déjeuner Léger',
                'name'           => 'Tajine Kefta',
                'name_ar'        => 'طاجين الكفتة',
                'description'    => 'Servi avec une entrée marocaine du jour et du pain maison',
                'image'          => 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 120.00,
                'price_achat'    => 45.00,
                'stock_quantity' => 30,
                'alert_stock'    => 6,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Déjeuner Léger',
                'name'           => 'Tajine de crevettes à la sauce Pil-Pil',
                'name_ar'        => 'طاجين الجمبري بصلصة البيل-بيل',
                'description'    => 'Servi avec des frites maison',
                'image'          => 'https://images.unsplash.com/photo-1519984388953-d2406bc725e1?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 100.00,
                'price_achat'    => 40.00,
                'stock_quantity' => 20,
                'alert_stock'    => 5,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Déjeuner Léger',
                'name'           => 'Spaghetti Bolognaise maison',
                'name_ar'        => 'سباغيتي بولونيز منزلي',
                'description'    => 'Spaghetti Bolognaise fait maison',
                'image'          => 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 85.00,
                'price_achat'    => 28.00,
                'stock_quantity' => 30,
                'alert_stock'    => 6,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Déjeuner Léger',
                'name'           => 'Sandwich maison (poulet ou viande hachée)',
                'name_ar'        => 'ساندويتش منزلي (دجاج أو لحم مفروم)',
                'description'    => 'Servi avec des frites maison et salade',
                'image'          => 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 80.00,
                'price_achat'    => 28.00,
                'stock_quantity' => 40,
                'alert_stock'    => 8,
                'unit'           => 'pièce',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Déjeuner Léger',
                'name'           => 'Sandwich maison au thon',
                'name_ar'        => 'ساندويتش منزلي بالتونة',
                'description'    => 'Servi avec des frites maison et salade',
                'image'          => 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 60.00,
                'price_achat'    => 20.00,
                'stock_quantity' => 40,
                'alert_stock'    => 8,
                'unit'           => 'pièce',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Déjeuner Léger',
                'name'           => 'Burger Fermier Oussoul',
                'name_ar'        => 'برغر أوسول الريفي',
                'description'    => 'Servi avec des frites maison',
                'image'          => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 85.00,
                'price_achat'    => 30.00,
                'stock_quantity' => 25,
                'alert_stock'    => 5,
                'unit'           => 'pièce',
                'kitchen_active' => 1,
            ],

            // ── Plats Marocains (Sur Réservation) ────────────────────────────
            [
                'category'       => 'Plats Marocains',
                'name'           => 'Tajine de poulet aux citrons confits et olives',
                'name_ar'        => 'طاجين الدجاج بالليمون المحفوظ والزيتون',
                'description'    => 'Servi avec une entrée marocaine du jour et du pain maison',
                'image'          => 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 110.00,
                'price_achat'    => 42.00,
                'stock_quantity' => 20,
                'alert_stock'    => 4,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Plats Marocains',
                'name'           => 'Tajine bœuf aux pruneaux',
                'name_ar'        => 'طاجين البقر بالبرقوق',
                'description'    => 'Servi avec une entrée marocaine du jour et du pain maison',
                'image'          => 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 130.00,
                'price_achat'    => 55.00,
                'stock_quantity' => 15,
                'alert_stock'    => 3,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Plats Marocains',
                'name'           => 'Tajine de poisson du Détroit à la chermoula',
                'name_ar'        => 'طاجين سمك المضيق بالشرمولة',
                'description'    => 'Selon l\'arrivage du jour',
                'image'          => 'https://images.unsplash.com/photo-1519984388953-d2406bc725e1?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 120.00,
                'price_achat'    => 48.00,
                'stock_quantity' => 12,
                'alert_stock'    => 3,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Plats Marocains',
                'name'           => 'Couscous bœuf',
                'name_ar'        => 'كسكس البقر',
                'description'    => 'Vendredi ou sur réservation pour 4 personnes',
                'image'          => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 90.00,
                'price_achat'    => 38.00,
                'stock_quantity' => 20,
                'alert_stock'    => 4,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Plats Marocains',
                'name'           => 'Couscous poulet',
                'name_ar'        => 'كسكس الدجاج',
                'description'    => 'Vendredi ou sur réservation pour 4 personnes',
                'image'          => 'https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 80.00,
                'price_achat'    => 32.00,
                'stock_quantity' => 25,
                'alert_stock'    => 5,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Plats Marocains',
                'name'           => 'Pastilla traditionnelle au poulet',
                'name_ar'        => 'البسطيلة التقليدية بالدجاج',
                'description'    => 'À partager — minimum 4 personnes',
                'image'          => 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 90.00,
                'price_achat'    => 38.00,
                'stock_quantity' => 10,
                'alert_stock'    => 2,
                'unit'           => 'pièce',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Plats Marocains',
                'name'           => 'Pastilla traditionnelle aux fruits de mer',
                'name_ar'        => 'البسطيلة التقليدية بالمأكولات البحرية',
                'description'    => 'À partager — minimum 4 personnes',
                'image'          => 'https://images.unsplash.com/photo-1519984388953-d2406bc725e1?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 90.00,
                'price_achat'    => 42.00,
                'stock_quantity' => 10,
                'alert_stock'    => 2,
                'unit'           => 'pièce',
                'kitchen_active' => 1,
            ],

            // ── Desserts ──────────────────────────────────────────────────────
            [
                'category'       => 'Desserts',
                'name'           => 'Assiette de fruits frais de saison',
                'name_ar'        => 'طبق فواكه طازجة موسمية',
                'description'    => 'Fruits frais de saison',
                'image'          => 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 60.00,
                'price_achat'    => 20.00,
                'stock_quantity' => 30,
                'alert_stock'    => 6,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Desserts',
                'name'           => 'Assortiment de pâtisseries marocaines',
                'name_ar'        => 'تشكيلة الحلويات المغربية',
                'description'    => '3 pièces',
                'image'          => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 45.00,
                'price_achat'    => 15.00,
                'stock_quantity' => 60,
                'alert_stock'    => 12,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Desserts',
                'name'           => 'Glace artisanale',
                'name_ar'        => 'آيس كريم حرفي',
                'description'    => '2 boules',
                'image'          => 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 40.00,
                'price_achat'    => 12.00,
                'stock_quantity' => 50,
                'alert_stock'    => 10,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Desserts',
                'name'           => 'Pancakes maison au chocolat',
                'name_ar'        => 'فطائر منزلية بالشوكولاتة',
                'description'    => 'Avec une boule de glace artisanale',
                'image'          => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 60.00,
                'price_achat'    => 20.00,
                'stock_quantity' => 30,
                'alert_stock'    => 6,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],

            // ── Menu Oussoul ──────────────────────────────────────────────────
            [
                'category'       => 'Menu Oussoul',
                'name'           => 'Formule Menu Oussoul',
                'name_ar'        => 'فورمولا منيو أصول',
                'description'    => 'Entrée marocaine ou salade du terroir, Tajine du jour, Assortiment de pâtisseries marocaines, Thé marocain aux herbes du jardin',
                'image'          => 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 180.00,
                'price_achat'    => 70.00,
                'stock_quantity' => 20,
                'alert_stock'    => 4,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],

            // ── Les Petits Plaisirs ───────────────────────────────────────────
            [
                'category'       => 'Les Petits Plaisirs',
                'name'           => 'Salade de fruits frais',
                'name_ar'        => 'سلطة فواكه طازجة',
                'description'    => 'Salade de fruits frais',
                'image'          => 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 25.00,
                'price_achat'    => 8.00,
                'stock_quantity' => 50,
                'alert_stock'    => 10,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Les Petits Plaisirs',
                'name'           => 'Muesli',
                'name_ar'        => 'موسلي',
                'description'    => 'Muesli',
                'image'          => 'https://images.unsplash.com/photo-1490818387583-1baba5e638af?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 25.00,
                'price_achat'    => 8.00,
                'stock_quantity' => 40,
                'alert_stock'    => 8,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Les Petits Plaisirs',
                'name'           => 'Fruits secs (Amandes et dattes)',
                'name_ar'        => 'فواكه جافة (لوز وتمر)',
                'description'    => 'Amandes et dattes',
                'image'          => 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 10.00,
                'price_achat'    => 4.00,
                'stock_quantity' => 80,
                'alert_stock'    => 15,
                'unit'           => 'portion',
                'kitchen_active' => 0,
            ],
            [
                'category'       => 'Les Petits Plaisirs',
                'name'           => 'Oeuf supplémentaire',
                'name_ar'        => 'بيضة إضافية',
                'description'    => 'Oeuf supplémentaire',
                'image'          => 'https://images.unsplash.com/photo-1518569656558-1f25e69d2490?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 10.00,
                'price_achat'    => 3.00,
                'stock_quantity' => 100,
                'alert_stock'    => 20,
                'unit'           => 'pièce',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Les Petits Plaisirs',
                'name'           => 'Oeuf au Khlie',
                'name_ar'        => 'بيض بالخليع',
                'description'    => 'Oeuf au Khlie (viande séchée traditionnelle)',
                'image'          => 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 25.00,
                'price_achat'    => 10.00,
                'stock_quantity' => 40,
                'alert_stock'    => 8,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Les Petits Plaisirs',
                'name'           => 'Fromage à tartiner',
                'name_ar'        => 'جبنة دهن',
                'description'    => 'Fromage à tartiner',
                'image'          => 'https://images.unsplash.com/photo-1618164436241-4473940d1f5c?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 5.00,
                'price_achat'    => 2.00,
                'stock_quantity' => 60,
                'alert_stock'    => 12,
                'unit'           => 'portion',
                'kitchen_active' => 0,
            ],
            [
                'category'       => 'Les Petits Plaisirs',
                'name'           => 'Fromage fermier du village',
                'name_ar'        => 'جبنة فلاحية من القرية',
                'description'    => 'Fromage fermier artisanal',
                'image'          => 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 10.00,
                'price_achat'    => 4.00,
                'stock_quantity' => 40,
                'alert_stock'    => 8,
                'unit'           => 'portion',
                'kitchen_active' => 0,
            ],
            [
                'category'       => 'Les Petits Plaisirs',
                'name'           => 'Pancakes maison',
                'name_ar'        => 'فطائر منزلية',
                'description'    => '2 pièces avec accompagnement',
                'image'          => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 25.00,
                'price_achat'    => 8.00,
                'stock_quantity' => 40,
                'alert_stock'    => 8,
                'unit'           => 'portion',
                'kitchen_active' => 1,
            ],
            [
                'category'       => 'Les Petits Plaisirs',
                'name'           => 'Amlou',
                'name_ar'        => 'أملو',
                'description'    => 'Amlou maison (amandes, argan, miel)',
                'image'          => 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 5.00,
                'price_achat'    => 2.00,
                'stock_quantity' => 60,
                'alert_stock'    => 12,
                'unit'           => 'portion',
                'kitchen_active' => 0,
            ],
            [
                'category'       => 'Les Petits Plaisirs',
                'name'           => 'Chocolat',
                'name_ar'        => 'شوكولاتة',
                'description'    => 'Chocolat',
                'image'          => 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 5.00,
                'price_achat'    => 2.00,
                'stock_quantity' => 60,
                'alert_stock'    => 12,
                'unit'           => 'portion',
                'kitchen_active' => 0,
            ],
            [
                'category'       => 'Les Petits Plaisirs',
                'name'           => 'Charcuterie',
                'name_ar'        => 'لحوم مصنعة',
                'description'    => 'Charcuterie',
                'image'          => 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 20.00,
                'price_achat'    => 8.00,
                'stock_quantity' => 40,
                'alert_stock'    => 8,
                'unit'           => 'portion',
                'kitchen_active' => 0,
            ],
            [
                'category'       => 'Les Petits Plaisirs',
                'name'           => 'Thon',
                'name_ar'        => 'تونة',
                'description'    => 'Thon',
                'image'          => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=640&q=80',
                'price_vente'    => 15.00,
                'price_achat'    => 5.00,
                'stock_quantity' => 50,
                'alert_stock'    => 10,
                'unit'           => 'portion',
                'kitchen_active' => 0,
            ],
        ];

        foreach ($produits as $p) {
            $cat = Category::where('name', $p['category'])->firstOrFail();

            Produit::updateOrCreate(
                ['name' => $p['name'], 'category_id' => $cat->id],
                [
                    'name_ar'        => $p['name_ar']        ?? null,
                    'name_en'        => $p['name_en']        ?? null,
                    'image'          => $p['image'],
                    'price_vente'    => $p['price_vente'],
                    'price_achat'    => $p['price_achat'],
                    'stock_quantity' => $p['stock_quantity'],
                    'alert_stock'    => $p['alert_stock'],
                    'unit'           => $p['unit'],
                    'status'         => 'active',
                    'kitchen_active' => $p['kitchen_active'] ?? 1,
                ]
            );
        }

        $this->command->info('ProduitsSeeder : ' . count($produits) . ' produits crees.');
    }
}
