services:
  app:
    build: .
    container_name: laravel_app
    command: php-fpm -R
    working_dir: /app
    volumes:
      - ./.env:/app/.env
      - app_storage_framework:/app/storage/framework
      - app_bootstrap_cache:/app/bootstrap/cache
    networks:
      - laravel_network
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:16-alpine
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-techmizane}
      POSTGRES_USER: ${DB_USERNAME:-techmizane}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel_network
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    container_name: laravel_adminer
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8081:8080"
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80"
      - "${HTTPS_PORT:-8443}:443"
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - laravel_network
    depends_on:
      app:
        condition: service_started

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    networks:
      - laravel_network
    ports:
      - "6379:6379"

networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  app_storage_framework:
    driver: local
  app_bootstrap_cache:
    driver: local

